repository_type: pipeline

nf_core_version: 3.3.2

lint:
  actions_schema_validation: false
  files_exist: false
  nextflow_config: false
  nf_test_content: false
  rocrate_readme_sync: false
  actions_ci: false
  files_unchanged:
    - .github/workflows/ci.yml
    - .github/workflows/nf-test.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .prettierrc.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_light.png
    - docs/images/nf-core-orfology_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config:
    - report_comment

template:
  org: shahcompbio
  name: wakcna
  description: Run Wakhan on phased SVs for copy number analysis
  author: Asher Preska Steinberg
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - fastqc
    - gpu
  is_nfcore: false
