name: nf-core CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    name: Job to run the test workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: 0.9.2
          install-pdiff: true

      - name: Run Tests
        run: nf-test test --verbose --profile test,docker
